webhook-created: &webhook-created
  name: Webhook created
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-created -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
webhook-failed: &webhook-failed
  name: Webhook completed
  when: on_fail
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-completed\&status\=FAILED -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
version: 2.1
jobs:
  webhook-completed:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Webhook completed
          command: |
            curl $BUILD_STATUS_URL\?flow\=circleci-completed -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_PREVIOUS_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
  build-python:
    docker:
      - image: circleci/python:3.7.3
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: pip install poetry==0.12.17
      - run: cd ~/project/dynabuffers-python && poetry install
      - run: cd ~/project/dynabuffers-python && poetry run test_ci
      - run: cd ~/project/dynabuffers-python && poetry build
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: chmod a+x gradlew
      - restore_cache:
          key: cache-gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: ./gradlew generateGrammarSource
      - run: ./gradlew test --stacktrace
      - run: find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} $TEST_RESULTS_PATH \;
      - run: ./gradlew assemble --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  release-python:
    docker:
      - image: circleci/python:3.7.3
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: pip install poetry==0.12.17
      - run: cd ~/project/dynabuffers-python && poetry install
      - run: cd ~/project/dynabuffers-python && poetry run release $CIRCLE_TAG
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  release-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - restore_cache:
          key: cache-gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew generateGrammarSource final bintrayUpload -Prelease.useLastTag=true --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-gradle-{{ checksum "build.gradle" }}
      - run:
          <<: *webhook-failed
  code-analytics:
    docker:
      - image: circleci/python:3.7.3
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: pip install poetry==0.12.17
      - run: cd ~/project/dynabuffers-python && poetry install
      - run: cd ~/project/dynabuffers-python && poetry run test_ci
      - run: cd ~/project/dynabuffers-python && poetry build
      - run: |
          curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          sonarqube=$(unzip -l sonar-scanner.zip | awk '{print $4}' | grep "^\([a-z0-9.-]*\/\)$")/bin/sonar-scanner
          ./$sonarqube -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=one.leftshift.dynabuffers -Dsonar.projectName=dynabuffers
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed

workflows:
  version: 2
  build:
    jobs:
      - build-java:
          context: bintray-jcenter
          filters:
            tags:
              ignore: /.*/
      - build-python:
          context: pypi
          filters:
            tags:
              ignore: /.*/
          requires:
            - build-java
      - webhook-completed:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build-python
  release:
    jobs:
      - release-python:
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release-java:
          context: bintray-jcenter
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - webhook-completed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
          requires:
            - release-java
  code-analytics:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - code-analytics:
          context: leftshiftone-sonar
      - webhook-completed:
          requires:
            - code-analytics
