package dynabuffers.header

import dynabuffers.exception.DynabuffersException

// This file is autogenerated from DynabuffersVersion.vm

class DynabuffersVersion(private val version: String) {

    companion object {
        val current = DynabuffersVersion("2.6.1")
    }

    fun getMajor(): Byte {
        try {
            val major = version.split('.')[0]
            return major.toByte()
        } catch (ex: Exception) {
            throw DynabuffersException("Dynabuffers major version cannot be extracted from: $version.\nReason: $ex")
        }
    }
}